apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "my-chart.serviceName" . | quote }}
  labels:
    {{- include "my-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | quote }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: "http"
      name: "http"
  selector:
    {{- include "my-chart.selectorLabels" . | nindent 4 }}
